# Generated by Django 5.0.7 on 2026-09-13 11:47

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GameListing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('game_name', models.CharField(max_length=200, verbose_name='game name')),
                ('price', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)], verbose_name='price')),
                ('condition', models.CharField(choices=[('new_in_shrink', 'New in Shrink'), ('like_new', 'Like New'), ('very_good', 'Very Good'), ('good', 'Good'), ('fair', 'Fair'), ('poor', 'Poor')], max_length=20, verbose_name='condition')),
                ('has_missing_pieces', models.BooleanField(default=False, verbose_name='has missing pieces')),
                ('smoking_household', models.BooleanField(default=False, verbose_name='exposed to smoking household')),
                ('musty_smell', models.BooleanField(default=False, verbose_name='has musty smell')),
                ('pet_exposure', models.CharField(blank=True, choices=[('cat', 'Cat'), ('dog', 'Dog'), ('multiple', 'Multiple pets')], help_text='Leave blank if the game was not exposed to any pets.', max_length=20, verbose_name='pet exposure')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='listings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['owner', 'created_at'], name='listings_ga_owner_i_dd5421_idx')],
            },
        ),
    ]
