# Generated by Django 5.0.7 on 2026-09-13 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelisting',
            name='comments',
            field=models.CharField(blank=True, max_length=64, verbose_name='comments'),
        ),
        migrations.AddField(
            model_name='gamelisting',
            name='missing_pieces_description',
            field=models.CharField(blank=True, help_text='Which piece(s) are missing, e.g. "2 red meeples, 1 die".', max_length=64, verbose_name='missing pieces description'),
        ),
    ]
