# Generated by Django 5.0.7 on 2026-09-14 01:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0002_gamelisting_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelisting',
            name='printed',
            field=models.BooleanField(default=False, help_text="Set automatically when an admin prints this listing's price tag. Admin-only - never exposed to or editable by the listing's owner, including via CSV import. Once True, only an admin can edit or delete the listing.", verbose_name='printed'),
        ),
    ]
