# Generated by Django 5.0.7 on 2026-09-15 01:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_gamelisting_printed'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamelisting',
            name='received',
            field=models.BooleanField(default=False, help_text="Whether the physical game has been received at the drop-off location. Admin-only - never exposed to or editable by the listing's owner, including via CSV import; toggled directly by an admin, unlike `printed` which is only ever set by the print actions.", verbose_name='received'),
        ),
    ]
