# Generated by Django 5.0.7 on 2026-09-12 17:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminSecuritySettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_whitelist_enabled', models.BooleanField(default=False)),
                ('session_timeout_minutes', models.PositiveIntegerField(default=15)),
            ],
            options={
                'verbose_name': 'Admin security settings',
                'verbose_name_plural': 'Admin security settings',
            },
        ),
        migrations.CreateModel(
            name='GeoRestrictionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('disabled', 'Disabled'), ('whitelist', 'Whitelist (allow only listed)'), ('blacklist', 'Blacklist (block listed)')], default='disabled', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Geo restriction settings',
                'verbose_name_plural': 'Geo restriction settings',
            },
        ),
        migrations.CreateModel(
            name='IPRestrictionSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mode', models.CharField(choices=[('disabled', 'Disabled'), ('whitelist', 'Whitelist (allow only listed)'), ('blacklist', 'Blacklist (block listed)')], default='disabled', max_length=16)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'IP restriction settings',
                'verbose_name_plural': 'IP restriction settings',
            },
        ),
        migrations.CreateModel(
            name='RegistrationCountryRestriction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Registration country restriction',
                'verbose_name_plural': 'Registration country restriction',
            },
        ),
        migrations.CreateModel(
            name='AdminAllowedIP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_or_cidr', models.CharField(max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_ips', to='security.adminsecuritysettings')),
            ],
            options={
                'unique_together': {('settings', 'ip_or_cidr')},
            },
        ),
        migrations.CreateModel(
            name='GeoRestrictionCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(help_text='ISO 3166-1 alpha-2, e.g. US, CA', max_length=2)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='countries', to='security.georestrictionsettings')),
            ],
            options={
                'unique_together': {('settings', 'country_code')},
            },
        ),
        migrations.CreateModel(
            name='IPRestrictionEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_or_cidr', models.CharField(help_text='e.g. 203.0.113.5 or 203.0.113.0/24', max_length=64)),
                ('note', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('settings', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='security.iprestrictionsettings')),
            ],
            options={
                'unique_together': {('settings', 'ip_or_cidr')},
            },
        ),
        migrations.CreateModel(
            name='RegistrationAllowedCountry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('country_code', models.CharField(max_length=2)),
                ('restriction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allowed_countries', to='security.registrationcountryrestriction')),
            ],
            options={
                'unique_together': {('restriction', 'country_code')},
            },
        ),
    ]
