# Generated by Django 5.0.7 on 2026-09-12 17:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('registration_attempt', 'Registration attempt'), ('password_change', 'Password change'), ('email_change', 'Email change'), ('role_change', 'Role change'), ('account_activation', 'Account activation'), ('geo_block', 'Geo block'), ('ip_block', 'IP block'), ('admin_action', 'Admin action')], max_length=32)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('actor', models.ForeignKey(blank=True, help_text='The user who performed or triggered this event, if known.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL)),
                ('target_user', models.ForeignKey(blank=True, help_text='The user affected by this event, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_targets', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['event_type', 'timestamp'], name='audit_audit_event_t_aa07a6_idx')],
            },
        ),
        migrations.CreateModel(
            name='LoginAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_attempted', models.EmailField(blank=True, max_length=254)),
                ('action', models.CharField(choices=[('login_success', 'Login success'), ('login_failure', 'Login failure'), ('logout', 'Logout')], max_length=20)),
                ('success', models.BooleanField(default=False)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, max_length=512)),
                ('country', models.CharField(blank=True, max_length=64)),
                ('city', models.CharField(blank=True, max_length=128)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_audits', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-timestamp'],
                'indexes': [models.Index(fields=['email_attempted', 'timestamp'], name='audit_login_email_a_172d7e_idx'), models.Index(fields=['ip_address', 'timestamp'], name='audit_login_ip_addr_4689ce_idx')],
            },
        ),
    ]
